name: foresight-macos
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - numpy
  - pillow
  - matplotlib
  - scikit-image
  - scikit-learn
  - pandas
  - tqdm
  - pip
  - pip:
      - pyimzml>=1.5
